package org.twelve.meridian.python;

import org.twelve.gcp.ast.AST;
import org.twelve.gcp.node.expression.Assignment;
import org.twelve.gcp.node.expression.OutlineDefinition;
import org.twelve.gcp.node.expression.Variable;
import org.twelve.gcp.node.expression.body.ProgramBody;
import org.twelve.gcp.node.expression.typeable.TypeNode;
import org.twelve.gcp.node.function.Argument;
import org.twelve.gcp.node.function.FunctionNode;
import org.twelve.gcp.node.imexport.Import;
import org.twelve.gcp.node.statement.OutlineDeclarator;
import org.twelve.gcp.node.statement.Statement;
import org.twelve.gcp.node.statement.VariableDeclarator;
import org.twelve.gcp.outline.Outline;

import java.util.List;

/**
 * Generates Python type stub ({@code .pyi}) content from a fully-inferred GCP {@link AST}.
 *
 * <p>The output follows PEP 484 stub format:
 * <pre>
 *   x: int
 *   def greet(name: str, age: int) -> str: ...
 *   class User:
 *       name: str
 *       age: int
 * </pre>
 */
public class TypeAnnotationGenerator {

    public String generate(AST ast) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by meridian-python — do not edit\n");
        sb.append("from __future__ import annotations\n\n");

        ProgramBody body = ast.program().body();
        for (Import imp : body.imports()) {
            appendImport(imp, sb, "");
        }
        for (Statement stmt : body.statements()) {
            appendStatement(stmt, sb, "");
        }
        return sb.toString();
    }

    // ── statement dispatch ─────────────────────────────────────────────────────

    private void appendStatement(Statement stmt, StringBuilder sb, String indent) {
        if (stmt instanceof VariableDeclarator vd) {
            appendVariableDeclarator(vd, sb, indent);
        } else if (stmt instanceof OutlineDeclarator od) {
            appendOutlineDeclarator(od, sb, indent);
        }
        // Return, ExpressionStatement etc. are not emitted in stubs
    }

    // ── variable / function ────────────────────────────────────────────────────

    private void appendVariableDeclarator(VariableDeclarator vd, StringBuilder sb, String indent) {
        for (Assignment assignment : vd.assignments()) {
            if (assignment.lhs() == null) continue;
            String name = assignment.lhs().lexeme().trim();
            if (name.isBlank()) continue;

            // If the assigned value is a FunctionNode, emit as def
            if (assignment.rhs() instanceof FunctionNode fn) {
                appendFunctionDef(name, fn, sb, indent);
            } else {
                // Plain variable: prefer declared type annotation over inferred
                TypeNode declared = (assignment.lhs() instanceof Variable v) ? v.declared() : null;
                Outline inferred  = assignment.rhs() != null ? assignment.rhs().outline() : null;
                String typeStr = resolveType(declared, inferred);
                sb.append(indent).append(name);
                if (typeStr != null) sb.append(": ").append(typeStr);
                sb.append(" = ...\n");
            }
        }
    }

    private void appendFunctionDef(String name, FunctionNode fn, StringBuilder sb, String indent) {
        sb.append(indent).append("def ").append(name).append("(");

        Argument arg = fn.argument();
        if (arg != null) {
            List<Argument> args = flattenArgs(arg);
            for (int i = 0; i < args.size(); i++) {
                if (i > 0) sb.append(", ");
                Argument a = args.get(i);
                String argName = a.lexeme().trim();
                String argType = resolveType(a.declared(), a.outline());
                sb.append(argName);
                if (argType != null) sb.append(": ").append(argType);
            }
        }
        sb.append(")");

        // Return type
        Outline returns = fn.outline();
        if (returns != null) {
            String retType = outlineToTypeStr(returns);
            if (retType != null) sb.append(" -> ").append(retType);
        }

        sb.append(": ...\n");
    }

    // ── outline / class ────────────────────────────────────────────────────────

    private void appendOutlineDeclarator(OutlineDeclarator od, StringBuilder sb, String indent) {
        List<OutlineDefinition> defs = od.definitions();
        if (defs.isEmpty()) return;

        // Use the first symbol name as the class name
        String className = defs.getFirst().symbolNode().lexeme().trim();
        sb.append(indent).append("class ").append(className).append(":\n");
        String childIndent = indent + "    ";

        boolean hasFields = false;
        for (OutlineDefinition def : defs) {
            String fieldName = def.symbolNode().lexeme().trim();
            if (fieldName.equals(className)) continue; // skip self-reference
            TypeNode typeNode = def.typeNode();
            if (typeNode != null) {
                sb.append(childIndent).append(fieldName)
                  .append(": ").append(typeNodeToStr(typeNode)).append("\n");
                hasFields = true;
            }
        }
        if (!hasFields) {
            sb.append(childIndent).append("...\n");
        }
        sb.append("\n");
    }

    // ── import ─────────────────────────────────────────────────────────────────

    private void appendImport(Import imp, StringBuilder sb, String indent) {
        // Use GCP's own lexeme which already formats the import statement
        sb.append(indent).append(imp.lexeme().trim()).append("\n");
    }

    // ── type resolution helpers ────────────────────────────────────────────────

    /**
     * Resolve a type string from a declared {@link TypeNode} (annotation) or inferred {@link Outline}.
     * Declared annotations take priority over inferred types.
     */
    private String resolveType(TypeNode declared, Outline inferred) {
        if (declared != null) {
            String s = typeNodeToStr(declared);
            if (s != null) return s;
        }
        if (inferred != null) {
            return outlineToTypeStr(inferred);
        }
        return null;
    }

    private String typeNodeToStr(TypeNode node) {
        if (node == null) return null;
        String lex = node.lexeme();
        return lex == null ? null : gcpTypeToPy(lex.trim());
    }

    private String outlineToTypeStr(Outline outline) {
        if (outline == null) return null;
        String name = outline.getClass().getSimpleName();
        // Map outline type class names to Python type names
        return switch (name) {
            case "INT"    -> "int";
            case "LONG"   -> "int";
            case "FLOAT"  -> "float";
            case "DOUBLE" -> "float";
            case "STRING" -> "str";
            case "BOOL"   -> "bool";
            case "UNIT"   -> "None";
            case "UNKNOWN", "NOTHING" -> null;
            default -> {
                // User-defined type: use the class name as-is
                String lex = outline.toString();
                yield lex != null && !lex.isBlank() ? gcpTypeToPy(lex.trim()) : null;
            }
        };
    }

    /** Translate GCP built-in type names to Python names. */
    private String gcpTypeToPy(String gcpType) {
        return switch (gcpType) {
            case "Int", "Long"         -> "int";
            case "Float", "Double"     -> "float";
            case "String"              -> "str";
            case "Bool"                -> "bool";
            case "Unit"                -> "None";
            case "Array"               -> "list";
            default                    -> gcpType;
        };
    }

    /**
     * Flatten a GCP {@link Argument} (which may represent a multi-parameter tuple)
     * into a flat list.
     */
    private List<Argument> flattenArgs(Argument arg) {
        // In GCP, a single Argument may represent the entire parameter list
        // as nested Argument nodes. For now, return it as a singleton.
        return List.of(arg);
    }
}
