package org.twelve.meridian.python;

import org.twelve.gcp.ast.AST;
import org.twelve.gcp.node.expression.Assignment;
import org.twelve.gcp.node.expression.OutlineDefinition;
import org.twelve.gcp.node.expression.Variable;
import org.twelve.gcp.node.expression.body.ProgramBody;
import org.twelve.gcp.node.expression.typeable.TypeNode;
import org.twelve.gcp.node.function.Argument;
import org.twelve.gcp.node.function.FunctionNode;
import org.twelve.gcp.node.imexport.Import;
import org.twelve.gcp.node.statement.OutlineDeclarator;
import org.twelve.gcp.node.statement.Statement;
import org.twelve.gcp.node.statement.VariableDeclarator;
import org.twelve.gcp.ast.Node;
import org.twelve.gcp.node.statement.ReturnStatement;
import org.twelve.meridian.python.converter.GeneratorYieldNode;
import org.twelve.gcp.outline.Outline;
import org.twelve.gcp.outline.adt.Array;
import org.twelve.gcp.outline.adt.Dict;
import org.twelve.gcp.outline.adt.Option;
import org.twelve.gcp.outline.adt.Tuple;
import org.twelve.gcp.outline.builtin.ERROR;
import org.twelve.gcp.outline.builtin.UNIT;
import org.twelve.gcp.outline.builtin.UNKNOWN;
import org.twelve.gcp.outline.primitive.*;
import org.twelve.gcp.outline.projectable.Genericable;
import org.twelve.gcp.outline.projectable.Function;
import org.twelve.gcp.outline.projectable.Genericable;
import org.twelve.gcp.outline.projectable.Projectable;

import java.util.ArrayList;
import java.util.List;

/**
 * Generates Python type stub ({@code .pyi}) content from a fully-inferred GCP {@link AST}.
 *
 * <p>The output follows PEP 484 stub format:
 * <pre>
 *   x: int
 *   def greet(name: str, age: int) -> str: ...
 *   class User:
 *       name: str
 *       age: int
 * </pre>
 */
public class TypeAnnotationGenerator {

    public String generate(AST ast) {
        // First pass: generate content to detect which typing imports are needed
        StringBuilder content = new StringBuilder();
        ProgramBody body = ast.program().body();
        for (Import imp : body.imports()) {
            appendImport(imp, content, "");
        }
        for (Statement stmt : body.statements()) {
            appendStatement(stmt, content, "");
        }
        String contentStr = content.toString();

        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by meridian-python — do not edit\n");
        sb.append("from __future__ import annotations\n");
        if (contentStr.contains("Iterator[")) {
            sb.append("from typing import Iterator\n");
        }
        if (contentStr.contains("Callable[")) {
            sb.append("from typing import Callable\n");
        }
        if (contentStr.contains("Optional[")) {
            sb.append("from typing import Optional\n");
        }
        if (contentStr.contains("Union[")) {
            sb.append("from typing import Union\n");
        }
        if (java.util.regex.Pattern.compile("\\bAny\\b").matcher(contentStr).find()) {
            sb.append("from typing import Any\n");
        }
        sb.append("\n").append(contentStr);
        return sb.toString();
    }

    // ── statement dispatch ─────────────────────────────────────────────────────

    private void appendStatement(Statement stmt, StringBuilder sb, String indent) {
        if (stmt instanceof VariableDeclarator vd) {
            appendVariableDeclarator(vd, sb, indent);
        } else if (stmt instanceof OutlineDeclarator od) {
            appendOutlineDeclarator(od, sb, indent);
        }
        // Return, ExpressionStatement etc. are not emitted in stubs
    }

    // ── variable / function ────────────────────────────────────────────────────

    private void appendVariableDeclarator(VariableDeclarator vd, StringBuilder sb, String indent) {
        for (Assignment assignment : vd.assignments()) {
            if (assignment.lhs() == null) continue;
            String name = assignment.lhs().lexeme().trim();
            if (name.isBlank()) continue;

            // If the assigned value is a FunctionNode, emit as def
            if (assignment.rhs() instanceof FunctionNode fn) {
                appendFunctionDef(name, fn, sb, indent);
            } else {
                // Plain variable: prefer declared type annotation over inferred
                TypeNode declared = (assignment.lhs() instanceof Variable v) ? v.declared() : null;
                Outline inferred  = assignment.rhs() != null ? assignment.rhs().outline() : null;
                String typeStr = resolveType(declared, inferred);
                sb.append(indent).append(name);
                if (typeStr != null) sb.append(": ").append(typeStr);
                sb.append(" = ...\n");
            }
        }
    }

    private void appendFunctionDef(String name, FunctionNode fn, StringBuilder sb, String indent) {
        sb.append(indent).append("def ").append(name).append("(");

        List<Argument> args = flattenFunctionArgs(fn);
        List<String> paramHints = new ArrayList<>();
        for (int i = 0; i < args.size(); i++) {
            if (i > 0) sb.append(", ");
            Argument a = args.get(i);
            String argName = a.name();   // use .name(), not .lexeme() which includes type annotation
            String argType = resolveType(a.declared(), a.outline());
            sb.append(argName);
            if (argType != null) {
                sb.append(": ").append(argType);
            } else {
                // Collect ⚠️ hint for params whose GCP type cannot be expressed as Python annotation
                String hint = outlineToHint(a.outline());
                if (hint != null) paramHints.add(argName + ": " + hint);
            }
        }
        sb.append(")");

        // Return type: navigate to the innermost FunctionNode, then read returns().supposedToBe()
        String retType = functionReturnType(fn);
        if (retType != null) sb.append(" -> ").append(retType);

        sb.append(": ...");
        if (!paramHints.isEmpty()) {
            sb.append("  # ⚠️ ").append(String.join(", ", paramHints));
        }
        sb.append("\n");
    }

    // ── outline / class ────────────────────────────────────────────────────────

    private void appendOutlineDeclarator(OutlineDeclarator od, StringBuilder sb, String indent) {
        List<OutlineDefinition> defs = od.definitions();
        if (defs.isEmpty()) return;

        // Use the first symbol name as the class name
        String className = defs.getFirst().symbolNode().lexeme().trim();
        sb.append(indent).append("class ").append(className).append(":\n");
        String childIndent = indent + "    ";

        boolean hasFields = false;
        for (OutlineDefinition def : defs) {
            String fieldName = def.symbolNode().lexeme().trim();
            if (fieldName.equals(className)) continue; // skip self-reference
            TypeNode typeNode = def.typeNode();
            if (typeNode != null) {
                sb.append(childIndent).append(fieldName)
                  .append(": ").append(typeNodeToStr(typeNode)).append("\n");
                hasFields = true;
            }
        }
        if (!hasFields) {
            sb.append(childIndent).append("...\n");
        }
        sb.append("\n");
    }

    // ── import ─────────────────────────────────────────────────────────────────

    private void appendImport(Import imp, StringBuilder sb, String indent) {
        // Use GCP's own lexeme which already formats the import statement
        sb.append(indent).append(imp.lexeme().trim()).append("\n");
    }

    // ── type resolution helpers ────────────────────────────────────────────────

    /**
     * Resolve a type string from a declared {@link TypeNode} (annotation) or inferred {@link Outline}.
     * Declared annotations take priority over inferred types.
     */
    private String resolveType(TypeNode declared, Outline inferred) {
        if (declared != null) {
            String s = typeNodeToStr(declared);
            if (s != null) return s;
        }
        if (inferred != null) {
            return outlineToTypeStr(inferred);
        }
        return null;
    }

    String typeNodeToStr(TypeNode node) {
        if (node == null) return null;
        String lex = node.lexeme();
        return lex == null ? null : gcpTypeToPy(lex.trim());
    }

    /**
     * Returns a GCP-level type description for display/hint purposes, for outlines that
     * cannot be expressed as a Python type annotation. Returns {@code null} when the
     * outline is already annotatable (see {@link #outlineToTypeStr}) or when no
     * meaningful GCP description is available.
     *
     * <p>Used to generate {@code # ⚠️} hint comments for parameters whose inferred type
     * cannot be written as a Python annotation — for example, an anonymous structural
     * entity inferred from member-access patterns such as {@code person.age}.
     */
    String outlineToHint(Outline outline) {
        if (outline == null) return null;
        if (outlineToTypeStr(outline) != null) return null; // already annotatable, no hint needed
        if (outline instanceof Genericable<?, ?> g) {
            Outline min = g.min();
            if (!(min instanceof ANY) && !(min instanceof NOTHING) && !(min instanceof UNKNOWN)
                    && !(min instanceof Genericable)) {
                if (min instanceof Function) return "Callable";
                if (min instanceof org.twelve.gcp.outline.adt.Entity e) return entityHint(e);
            }
        }
        if (outline instanceof org.twelve.gcp.outline.adt.Entity e) return entityHint(e);
        return null;
    }

    private String entityHint(org.twelve.gcp.outline.adt.Entity e) {
        List<String> names = e.members().stream()
                .map(m -> m.name())
                .filter(n -> n != null && !n.isBlank())
                .toList();
        if (names.isEmpty()) return "Entity";
        return "Entity{" + String.join(", ", names) + "}";
    }

    /**
     * Convert a GCP inferred {@link Outline} type to its Python type string.
     * Uses {@code instanceof} checks on the GCP type hierarchy rather than
     * fragile class-name matching.
     */
    String outlineToTypeStr(Outline outline) {
        if (outline == null) return null;
        if (outline instanceof UNKNOWN || outline instanceof NOTHING) return null;
        if (outline instanceof ERROR) return null;
        // Function outlines → Python Callable[[arg, ...], ret]
        if (outline instanceof Function<?, ?> f) {
            return functionOutlineToCallable(f);
        }
        // A Genericable is a type-variable placeholder.  Resolve via a three-level priority chain:
        //   1. min() — strongest lower-bound constraint (hasToBe / definedToBe / declaredToBe)
        //   2. projectedType() — concrete entity recorded after a successful projectEntity pass
        //      (e.g. a lambda parameter after call-site projection, even when hasToBe is ANY)
        //   3. max() — upper bound from the actual assigned value (e.g. x=100 → Integer)
        //      only used as last resort to avoid emitting over-general types
        if (outline instanceof Genericable<?, ?> g) {
            Outline min = g.min();
            if (!(min instanceof ANY) && !(min instanceof NOTHING) && !(min instanceof UNKNOWN)
                    && !(min instanceof Genericable)) {
                return outlineToTypeStr(min);
            }
            // Priority 2: concrete entity from call-site projection
            Outline projected = g.projectedType();
            if (projected != null && !(projected instanceof ANY) && !(projected instanceof UNKNOWN)
                    && !(projected instanceof Genericable)) {
                return outlineToTypeStr(projected);
            }
            // Priority 3: upper bound from actual assigned value (local variable scenario)
            Outline max = g.max();
            if (!(max instanceof NOTHING) && !(max instanceof ANY) && !(max instanceof UNKNOWN)
                    && !(max instanceof Genericable)) {
                return outlineToTypeStr(max);
            }
            return null;
        }
        // Named user-defined Entity (from a Python class declaration, e.g. `class User:`).
        // Entity implements Projectable, so this check MUST come before the Projectable guard
        // below — otherwise ALL entity types would be silently dropped.
        //
        // Two sub-cases:
        //   · Named entity — EntityTypeNodeInference creates the entity with node = EntityTypeNode.
        //     That EntityTypeNode's parent is an OutlineDefinition whose symbolNode() carries
        //     the Python class name (e.g. "Pet").  We navigate the parent chain to retrieve it.
        //   · Anonymous structural entity — created by MemberAccessorInference from a
        //     definedToBe constraint (e.g. ent.name → Entity({name:…})).  The node is a
        //     Variable/Identifier, not EntityTypeNode, so no Python class name is available.
        //     Return null; the parameter is left unannotated (known limitation).
        if (outline instanceof org.twelve.gcp.outline.adt.Entity e) {
            org.twelve.gcp.ast.Node entityNode = e.node();
            if (entityNode instanceof org.twelve.gcp.node.expression.typeable.EntityTypeNode) {
                org.twelve.gcp.ast.Node parent = entityNode.parent();
                if (parent instanceof org.twelve.gcp.node.expression.OutlineDefinition od) {
                    String className = od.symbolNode().lexeme().trim();
                    if (!className.isBlank()) return className;
                }
            }
            return null;
        }
        // The following concrete types all implement Projectable (via SumADT or DictOrArray),
        // so they MUST be checked before the Projectable guard below — otherwise they would
        // all be silently filtered out as "GCP runtime protocol" types.
        //
        //   · Option  (sum type)  → extends SumADT implements Projectable
        //   · Tuple / Array / Dict → extend DictOrArray implements Projectable
        if (outline instanceof Option o) {
            // Collect all resolvable member types:
            //   · 1 resolvable member  → Optional[X]
            //   · 2+ resolvable members → Union[X, Y, …]
            java.util.List<String> parts = new java.util.ArrayList<>();
            for (Outline opt : o.options()) {
                String s = outlineToTypeStr(opt);
                if (s != null) parts.add(s);
            }
            if (parts.isEmpty()) return null;
            if (parts.size() == 1) return "Optional[" + parts.getFirst() + "]";
            return "Union[" + String.join(", ", parts) + "]";
        }
        if (outline instanceof Tuple t) {
            java.util.Map<Integer, org.twelve.gcp.outline.Outline> structure = t.structure();
            List<Integer> indices = structure.keySet().stream()
                    .filter(i -> i >= 0).sorted().toList();
            if (indices.isEmpty()) return "tuple";
            List<String> parts = new ArrayList<>();
            for (Integer i : indices) {
                String s = outlineToTypeStr(structure.get(i));
                // Use "Any" for unresolved elements rather than degrading the whole tuple.
                // The caller (generate / rewrite) detects "Any" and injects the typing import.
                parts.add(s != null ? s : "Any");
            }
            return "tuple[" + String.join(", ", parts) + "]";
        }
        if (outline instanceof Array a) {
            String inner = outlineToTypeStr(a.itemOutline());
            return inner != null ? "list[" + inner + "]" : "list";
        }
        if (outline instanceof Dict d) {
            String k = outlineToTypeStr(d.key());
            String v = outlineToTypeStr(d.value());
            if (k != null && v != null) return "dict[" + k + ", " + v + "]";
            return "dict";
        }
        // Other Projectable outlines (Addable, OperateAble, etc.) are GCP runtime protocols,
        // not Python types — mypyc infers the concrete type from operand types in the body
        if (outline instanceof Projectable) return null;
        if (outline instanceof UNIT) return "None";
        if (outline instanceof BOOL)    return "bool";
        if (outline instanceof INTEGER) return "int";
        if (outline instanceof LONG)    return "int";
        if (outline instanceof FLOAT)   return "float";
        if (outline instanceof DECIMAL) return "float";
        if (outline instanceof DOUBLE)  return "float";
        if (outline instanceof NUMBER)  return "float";
        if (outline instanceof STRING)  return "str";
        // Named / user-defined type: use outline's semantic name
        String name = outline.name();
        return (name != null && !name.isBlank()) ? name : null;
    }

    /**
     * Like {@link #outlineToTypeStr} but intentionally skips the {@code max()} (extendToBe)
     * fallback. Used for function parameters where {@code extendToBe} is set by body inference
     * (e.g., the {@code +} operator sets it to {@code Union[str, float]}) and therefore is
     * too broad to use as a parameter annotation.
     *
     * <p>Parameter annotations should only rely on lower-bound constraints ({@code hasToBe} /
     * {@code definedToBe} via {@code min()}) or call-site projection ({@code projectedType()}).
     * If neither is available, call-site analysis will supply the type later.
     */
    String outlineToTypeStrForParam(Outline outline) {
        if (outline == null) return null;
        if (outline instanceof UNKNOWN || outline instanceof NOTHING) return null;
        if (outline instanceof ERROR) return null;
        if (outline instanceof Function<?, ?> f) {
            return functionOutlineToCallable(f);
        }
        if (outline instanceof Genericable<?, ?> g) {
            Outline min = g.min();
            // Skip SumADT (Option/Poly) in min(): these come from body-inference operator overloads
            // (e.g. definedToBe = Option({String, Number}) from `total += m`) and are too broad
            // to use as parameter annotations. Let call-site analysis supply the concrete type.
            if (!(min instanceof ANY) && !(min instanceof NOTHING) && !(min instanceof UNKNOWN)
                    && !(min instanceof Genericable)
                    && !(min instanceof org.twelve.gcp.outline.adt.SumADT)) {
                return outlineToTypeStr(min);
            }
            Outline projected = g.projectedType();
            if (projected != null && !(projected instanceof ANY) && !(projected instanceof UNKNOWN)
                    && !(projected instanceof Genericable)) {
                return outlineToTypeStr(projected);
            }
            return null; // No max() fallback — let call-site analysis fill it in
        }
        // Bare SumADT (Option/Poly) outlines for parameters come from body-inference extendToBe.
        // Leave them unannotated and let call-site analysis supply the concrete type.
        if (outline instanceof org.twelve.gcp.outline.adt.SumADT) return null;
        return outlineToTypeStr(outline);
    }

    /**
     * Convert a GCP {@link Function} outline (which is curried) to Python's
     * {@code Callable[[arg1, arg2, ...], ret]} syntax.
     *
     * <p>GCP represents multi-parameter functions as curried chains:
     * {@code fn(a) → fn(b) → fn(c) → body}.  We flatten the chain to collect
     * all argument types, then emit {@code Callable[[a, b, c], ret]}.
     *
     * <p>Returns {@code null} when any argument or the return type cannot be
     * expressed as a concrete Python type (e.g. still unresolved Genericable).
     */
    private String functionOutlineToCallable(Function<?, ?> f) {
        List<String> argTypes = new ArrayList<>();
        Function<?, ?> curr = f;
        while (true) {
            String argType = outlineToTypeStr(curr.argument());
            // Use "Any" for unresolved argument types rather than abandoning the whole Callable.
            // e.g. a HOF parameter whose argument type hasn't been narrowed by call-site inference
            // becomes Callable[[Any], int] instead of being completely unannotated.
            // The caller (generate / rewrite) detects "Any" and injects the typing import.
            argTypes.add(argType != null ? argType : "Any");
            Outline ret = curr.returns().supposedToBe();
            if (ret instanceof Function<?, ?> nested) {
                curr = nested;
            } else {
                String retType = outlineToTypeStr(ret);
                if (retType == null) retType = "Any";
                return "Callable[[" + String.join(", ", argTypes) + "], " + retType + "]";
            }
        }
    }

    /** Translate GCP type-annotation lexeme strings to Python names. */
    private String gcpTypeToPy(String gcpType) {
        if (gcpType == null) return null;
        return switch (gcpType) {
            case "Int", "Integer", "Long"   -> "int";
            case "Float", "Double", "Decimal", "Number" -> "float";
            case "String"                   -> "str";
            case "Bool"                     -> "bool";
            case "Unit", "Nothing"          -> "None";
            case "Array"                    -> "list";
            default                         -> gcpType;
        };
    }

    // ── curried-function traversal helpers ────────────────────────────────────

    /**
     * Extract the Python return-type string from a (possibly curried) {@link FunctionNode}.
     * <p>
     * GCP represents a multi-parameter function as a chain of curried {@link FunctionNode}s
     * ({@code FunctionNode.from(body, a, b, c)} builds {@code fn(a) { return fn(b) { return fn(c) { body } } }}).
     * The actual return type lives in the <em>innermost</em> node's inferred outline.
     */
    String functionReturnType(FunctionNode fn) {
        FunctionNode innermost = getInnermostFn(fn);
        Outline fnOutline = innermost.outline();
        if (fnOutline instanceof Function<?, ?> f) {
            Outline ret = f.returns().supposedToBe();
            if (isGeneratorFunction(innermost) && ret instanceof Array a) {
                String inner = outlineToTypeStr(a.itemOutline());
                return inner != null ? "Iterator[" + inner + "]" : "Iterator";
            }
            return outlineToTypeStr(ret);
        }
        return null;
    }

    /** Returns {@code true} when any return statement in the function body yields via a generator. */
    private static boolean isGeneratorFunction(FunctionNode fn) {
        for (Node child : fn.body().nodes()) {
            if (child instanceof ReturnStatement rs
                    && rs.expression() instanceof GeneratorYieldNode) {
                return true;
            }
        }
        return false;
    }

    /**
     * Flatten the curried-function chain into a flat list of {@link Argument}s,
     * skipping GCP's synthetic unit argument {@code ()}.
     */
    List<Argument> flattenFunctionArgs(FunctionNode fn) {
        List<Argument> result = new ArrayList<>();
        FunctionNode current = fn;
        while (current != null) {
            Argument arg = current.argument();
            if (arg != null) {
                String n = arg.name();
                if (n != null && !n.trim().equals("()") && !n.trim().isEmpty()) {
                    result.add(arg);
                }
            }
            current = extractCurriedNext(current);
        }
        return result;
    }

    private FunctionNode getInnermostFn(FunctionNode fn) {
        FunctionNode current = fn;
        FunctionNode next;
        while ((next = extractCurriedNext(current)) != null) {
            current = next;
        }
        return current;
    }

    /** If {@code fn}'s body is a single {@code return <FunctionNode>}, return that nested node. */
    private static FunctionNode extractCurriedNext(FunctionNode fn) {
        for (Node child : fn.body().nodes()) {
            if (child instanceof ReturnStatement rs
                    && rs.expression() instanceof FunctionNode nested) {
                return nested;
            }
        }
        return null;
    }
}
